var clinicLst = [
    {'name': 'FMC - Swiss Avenue',
     'addr': '2613 Swiss Ave, Dallas, TX 75204',
     'id': 1},
    {'name': 'DaCita DAVITA Downtown Dallas Dialysis',
     'addr': '3515 Swiss Ave Ste A, Dallas, TX 75204',
     'id': 2},
    {'name': 'FMC - Dallas East',
     'addr': '3604 Live Oak St, Dallas, TX 75204',
     'id': 3},
    {'name': 'US Renal Care Liberty Gaston',
     'addr': '3417 Gaston Avenue, Dallas, TX 75204',
     'id': 4},
    {'name': 'FMC - Dallas South',
     'addr': '1150 N Bishop Ave Ste 200, Dallas, TX 75208',
     'id': 5},
    {'name': 'DaVita Lake Cliff Dialysis Center',
     'addr': '805 N Beckley Ave, Dallas, TX 75203',
     'id': 6},
    {'name': 'Childrens Medical Center Dallas Dialysis Unit',
     'addr': '1935 Medical District Dr, Dallas, TX 75235',
     'id': 7},
    {'name': 'DaVita Oak Cliff Dialysis',
     'addr': '2000 S Llewellyn Ave, Dallas, TX 75224',
     'id': 8},
    {'name': 'DaVita Ut Southwestern-oakcliff Dialysis',
     'addr': '610 Wynnewood Dr, Dallas, TX 75224',
     'id': 9},
    {'name': 'FMC - Southwestern',
     'addr': '6010 Forest Park Rd, Dallas, TX 75235',
     'id': 10},
    {'name': 'FMC - Forest Park',
     'addr': '6010 Forest Park Rd Suite 100, Dallas, TX 75235',
     'id': 11},
    {'name': 'FMC - South Oak Cliff',
     'addr': '655 W Illinois Ave Suite 740 740 Wynnewood Village Shp Ctr, Dallas, TX 75224',
     'id': 12},
    {'name': 'DaVita Brookriver At Home',
     'addr': '8101 Brookriver Dr, Dallas, TX 75247',
     'id': 13},
    {'name': 'DaVita Brookriver Dialysis',
     'addr': '8101 Brookriver Dr, Dallas, TX 75247',
     'id': 14},
    {'name': 'VA Medical Center Dialysis Unit',
     'addr': '4500 S Lancaster Rd, Dallas, TX 75216',
     'id': 15},
    {'name': 'Dallas Nephrology',
     'addr': '1420 Viceroy Drive, Dallas, TX 75235',
     'id': 16},
    {'name': 'FMC Mockingbird PD',
     'addr': '8700 N Stemmons Fwy Suite 130, Dallas, TX 75247',
     'id': 17},
    {'name': 'FMC - Village 2 Dialysis',
     'addr': '6300 Samuell Blvd, Dallas, TX 75228',
     'id': 18},
    {'name': 'ARA - Kessler Park Regional Dialysis Center',
     'addr': '1070 N Westmoreland Rd, Dallas, TX 75211',
     'id': 19},
    {'name': 'FMC - Dallas Central',
     'addr': '7610 Military Pkwy, Dallas, TX 75227',
     'id': 20},
    {'name': 'FMC Kiest Station',
     'addr': '5148 S Lancaster Rd Suite B, Dallas, TX 75241',
     'id': 21},
    {'name': 'FMC - South Dallas County',
     'addr': '1111 W Ledbetter Dr Ste 800, Dallas, TX 75224',
     'id': 22},
    {'name': 'FMC - North Buckner',
     'addr': '3650 N Buckner Blvd, Dallas, TX 75228',
     'id': 23},
    {'name': 'DaVita Dallas East Dialysis',
     'addr': '3402 N Buckner Blvd Ste 308, Dallas, TX 75228',
     'id': 24},
    {'name': 'DaVita DAVITA Central Dallas Dialysis',
     'addr': '9500 N Central Expy Ste 102, Dallas, TX 75231',
     'id': 25},
    {'name': 'Cockrell Hill Dialysis',
     'addr': '4810 W Illinois Avenue, Dallas, TX 75211',
     'id': 26},
    {'name': 'FMC - Walnut Hill',
     'addr': '9850 N Central Expy, Dallas, TX 75231',
     'id': 27},
    {'name': 'US Renal Care North Dallas',
     'addr': '10740 N Central Expressway Suite 150, Dallas, TX 75231',
     'id': 28},
    {'name': 'Liberty Dialysis At Home',
     'addr': '5535 Red Bird Center Dr. Suite 150, Dallas, TX 75237',
     'id': 29},
    {'name': 'FMC - Redbird',
     'addr': '4111 W Camp Wisdom Rd, Dallas, TX 75237',
     'id': 30}
  ];
  
  export {clinicLst};