var clinicLst = [
  {'name': 'FMC - Swiss Avenue',
   'addr': '2613 Swiss Ave, Dallas, TX 75204',
   'id': 1},
  {'name': 'DaCita DAVITA Downtown Dallas Dialysis',
   'addr': '3515 Swiss Ave Ste A, Dallas, TX 75204',
   'id': 2},
  {'name': 'FMC - Dallas East',
   'addr': '3604 Live Oak St, Dallas, TX 75204',
   'id': 3},
  {'name': 'US Renal Care Liberty Gaston',
   'addr': '3417 Gaston Avenue, Dallas, TX 75204',
   'id': 4},
  {'name': 'FMC - Dallas South',
   'addr': '1150 N Bishop Ave Ste 200, Dallas, TX 75208',
   'id': 5},
  {'name': 'DaVita Lake Cliff Dialysis Center',
   'addr': '805 N Beckley Ave, Dallas, TX 75203',
   'id': 6},
  {'name': 'Childrens Medical Center Dallas Dialysis Unit',
   'addr': '1935 Medical District Dr, Dallas, TX 75235',
   'id': 7},
  {'name': 'DaVita Oak Cliff Dialysis',
   'addr': '2000 S Llewellyn Ave, Dallas, TX 75224',
   'id': 8},
  {'name': 'DaVita Ut Southwestern-oakcliff Dialysis',
   'addr': '610 Wynnewood Dr, Dallas, TX 75224',
   'id': 9},
  {'name': 'FMC - Southwestern',
   'addr': '6010 Forest Park Rd, Dallas, TX 75235',
   'id': 10}
];

export {clinicLst};